runtime: nodejs24  # or nodejs22 if you want a stable supported non-preview version; App Engine auto-updates minor/patch. 
env: flex
resources:
  cpu: 0.5
  memory_gb: 1
  disk_size_gb: 4

env_variables:
  NODE_ENV: production
  # other tenant-specific vars can be injected here or via secrets proxy